message: Welcome to Configuration Server

---

spring:
  profiles: dev
  app: basquiatDev
message: Welcom to basquiatDev

couchbase:
  bucket:
    name: basquiat
    password: basquiat
    ip: localhost
    expiry: 0

---

spring:
  profiles: stage
  app: basquiatStage
message: Welcom to basquiatStage

couchbase:
  bucket:
    name: basquiat
    password: basquiat
    ip: stage-id
    expiry: 0
---

spring:
  profiles: prod
  app: basquiatProd
message: Welcom to basquiatProd

couchbase:
  bucket:
    name: basquiat
    password: basquiat
    ip: prod-id
    expiry: 0