message: Welcome to Configuration Server

---

spring:
  profiles: dev
  app: basquiatDev
message: Welcom to basquiatDev

couchbase:
  bucket:
    name: basquiat
    password: basquiat
    ip: localhost
    expiry: 0

redis:
  host: localhost
  port: 6379

---

spring:
  profiles: stage
  app: basquiatStage
message: Welcom to basquiatStage

couchbase:
  bucket:
    name: <<stage-bucket-name>>
    ip: <<stage-bucket-ip>>
    password: <<stage-bucket-password>>
    expiry: <<yoursExpiry>>
    
redis:
  host: <<stage-redis-host>>
  port: <<stage-redis-port>>
---

spring:
  profiles: prod
  app: basquiatProd
message: Welcom to basquiatProd

couchbase:
  bucket:
    name: <<prod-bucket-name>>
    ip: <<prod-bucket-ip>>
    password: <<prod-bucket-password>>
    expiry: <<yoursExpiry>>
    
redis:
  host: <<prod-redis-host>>
  port: <<prod-redis-port>>